Added Linux build

diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -28,7 +28,7 @@ jobs:
           toolchain: stable
           components: rustfmt, clippy
 
-       # Cache Rust build
+      # Cache Rust build
       - name: Cache Rust build
         uses: actions/cache@v4
         with:
@@ -42,8 +42,7 @@ jobs:
       - name: Install cargo-c
         run: cargo install cargo-c
 
-
-        # Set up Go (for building the Go program)
+      # Set up Go (for building the Go program)
       - name: Set up Go
         uses: actions/setup-go@v4
         with:
@@ -52,14 +51,30 @@ jobs:
       - name: Clone YARA-X repository
         run: git clone https://github.com/VirusTotal/yara-x.git
 
-      - name: Checkout YARA-X version
+      - name: Build YARA-X C API and verify .pc file
         run: |
           cd yara-x
-          git checkout tags/v0.9.0
           cargo cinstall -p yara-x-capi --release --destdir=$HOME/yara_install
+          # Verify if the .pc file exists
+          if [ ! -f $HOME/yara_install/lib/pkgconfig/yara_x_capi.pc ]; then
+            echo "Error: yara_x_capi.pc not found in $HOME/yara_install/lib/pkgconfig"
+            exit 1
+          fi
+          # Debug output to verify files are correctly installed
+          ls -l $HOME/yara_install/lib/pkgconfig
+          ls -l $HOME/yara_install/lib
+          ls -l $HOME/yara_install/include
 
       - name: Clone FileTrove repository
         run: git clone https://github.com/steffenfritz/FileTrove.git
+
+      - name: Set environment variables for pkg-config and Go
+        run: |
+          export PKG_CONFIG_PATH=$HOME/yara_install/lib/pkgconfig
+          export CGO_CFLAGS="-I$HOME/yara_install/include"
+          export CGO_LDFLAGS="-L$HOME/yara_install/lib"
+          # Verify pkg-config can find the yara_x_capi package
+          pkg-config --cflags --libs yara_x_capi
 
       - name: Build Go Binary
         run: |
@@ -74,10 +89,8 @@ jobs:
 
       - name: Copy artifacts
         run: |
-
           cp $HOME/yara_install/lib/libyara_x_capi* ../artifacts/
           cp ./ftrove ../artifacts/
-
 
       - name: Create archive of artifacts
         run: |
